### ISSUE TITLE
Gerar HTML da Programação

### ISSUE THREAD

**Issue by tsosouza** [ppKrauss/SBPqO-2015#11]
A partir dos csv's entregues com a programação (programacaoEventos.csv e programacaoGrupoDia.csv), gerar HTML, se possível seguindo o template template_programacao.html. As informações de sala devem ter class="location1" e idref=[id da sala].

**Comment by ppKrauss** [comment]
Ver primeiro teste em [amostras/testeProgramacao.htm](https://github.com/ppKrauss/SBPqO-2015/blob/master/amostras/testeProgramacao.htm), foi gerado a partir de [xcsvProgramacao2htm.xsl](https://github.com/ppKrauss/SBPqO-2015/blob/master/src/xsl/xcsvProgramacao2htm.xsl)... Fique a vontade para alterar, o XML  de input desse XSLT é  [testeProgramacao.xml](https://github.com/ppKrauss/SBPqO-2015/blob/master/amostras/testeProgramacao.xml).

**Comment by tsosouza** [comment]
Primeiro teste ficou bom, com pequenos problemas:
- titulo dos menus deviam ser obtidos do progamacaoGrupoDia.csv
- remover PROGRAMACAO de cada titulo
- remover "- h" de eventos que não possuem horário de término
- colocar os ids das salas

Com exceção do último, o restante foi corrigido manualmente no arquivo gerado. Podemos corrigir no xsl depois se necessário.

**Comment by ppKrauss** [comment]
Fico devendo os IDs das salas (ver inclusao de novo csv para locais e seus ids globais), XSLT corrigido com o restante das solicitações.
