### ISSUE TITLE
Tratar locais no conteúdo extra de Instruções para Autores

### ISSUE THREAD

**Issue by tsosouza** [ppKrauss/SBPqO-2015#12]
No HTML de Instruções para Autores (https://github.com/ppKrauss/SBPqO-2015/tree/master/entregas/conteudoExtra/InstrucoesAutores), colocar o idref correto nas tags de local, se for possível fazer de forma automática.
O HTML já está formatado para ser inserido no app, restando somente a correção dos locais, que pode ser feito manualmente caso não seja possível automatizar.

**Comment by ppKrauss** [comment]
Atualizado, conferir:
- (ver se consistente e se HTML precisa correcoes) https://github.com/ppKrauss/SBPqO-2015/blob/master/instrucoes_dumps.txt
- (navegar e ver onde HTML seria alterado) https://github.com/ppKrauss/SBPqO-2015/blob/master/entregas/conteudoExtra/InstrucoesAutores/instrucoes_autores_teste.html

se tudo ok, automatizaremos a validação de consistência e a normalização do texto.

**Comment by tsosouza** [comment]
Problemas encontrados nessa amostra (html):
- Parser está varrendo somente os PNs. Precisamos alterar os "idref" de todas as apresentações, não somente PN.
- Nas tabelas, parser não está encontrando todas as salas. Encontra somente a da primeira linha.

Lembrando que o objetivo do tratamento, para o app, é a substuição do "idref" dos locations, somente.

**Comment by ppKrauss** [comment]
`instrucoes_autores_teste.html` (que substituiu o original) com texto normalizado e _IDloc_ indicado foi gerado, trabalho concluído na sexta.

---

Hoje foi gerado novo relatório de consistência entre `instrucoes_autores.html` e `instrucoes_autores.csv`, está em [instrucoes_dumps.txt](https://github.com/ppKrauss/SBPqO-2015/blob/master/entregas/conteudoExtra/InstrucoesAutores/instrucoes_dumps.txt): pode-se verificar por ele se tudo ok, não apareceu nenhuma mensagem de erro (!) apenas de "CONFERIR"... 

Infelizmente não foi possível impor via DOM a localização a partir do range (tabela CSV), pois no layout, em muitos casos, a informação de local vem depois do range, em outra TD.
