### ISSUE TITLE
Entrega EP1.1 comprometida, falhas de 2014 persistem 

### ISSUE THREAD

**Issue by ppKrauss** [ppKrauss/SBPqO-2015#7]
As supostas "falhas menores" de EP1.1 foram inicialmente tomadas como aceitáveis.

Olhando com mais cuidado na geração do PDF, todavia, foram observados erros que se propagam. Rastreando os avisos do _parser_ descobriu-se que **são falhas de 2014, não são "falhas menores"**: sinais de "&amp;" , "&lt;" e "&gt;" usados incorretamente (não-tag e não-entidade).

EXEMPLO, em [HTM1/AO.html versão 2015-07-31](https://github.com/ppKrauss/SBPqO-2015/blob/5fee29f0b63ae0561bae40c57ec1bd12edb3c2af/entregas/HTM1/AO.html)

  RESUMO AO0009:  "Bland & Altman" deveria ser "Bland &amp;amp; Altman"

  RESUMO AO0013: "no G1, T2 (0,26; 0,14-0,30) < T1 (0,32; 0,18-0,37) (P=0,046); no G2, T3 (0,20; 0,15-0,30) < T2"  deveria ser
     "no G1, T2 (0,26; 0,14-0,30) &amp;lt; T1 (0,32; 0,18-0,37) (P=0,046); no G2, T3 (0,20; 0,15-0,30) &amp;lt; T2"

**Sugestão**: efetuar correção find/replace global com supervisão humana a partir de padrões como " < ", " & ", "p<", etc. Muitas das falhas são repetidas.
## LISTA COMPLETA

 -- (raw) entregas/HTM1/AO.html
htmlParseEntityRef: no name in Entity, line: 24
htmlParseStartTag: invalid element name in Entity, line: 32
htmlParseStartTag: invalid element name in Entity, line: 138
htmlParseStartTag: invalid element name in Entity, line: 138
htmlParseStartTag: invalid element name in Entity, line: 138
htmlParseStartTag: invalid element name in Entity, line: 154
htmlParseStartTag: invalid element name in Entity, line: 180
htmlParseStartTag: invalid element name in Entity, line: 202
htmlParseStartTag: invalid element name in Entity, line: 216
Unexpected end tag : i in Entity, line: 216
htmlParseEntityRef: no name in Entity, line: 220
htmlParseStartTag: invalid element name in Entity, line: 242
htmlParseStartTag: invalid element name in Entity, line: 274
htmlParseStartTag: invalid element name in Entity, line: 286
htmlParseStartTag: invalid element name in Entity, line: 308
htmlParseEntityRef: no name in Entity, line: 424

 -- (raw) entregas/HTM1/COL.html
htmlParseStartTag: invalid element name in Entity, line: 16
htmlParseEntityRef: no name in Entity, line: 33
htmlParseEntityRef: no name in Entity, line: 33
htmlParseEntityRef: no name in Entity, line: 33
htmlParseStartTag: invalid element name in Entity, line: 36
Unexpected end tag : sub in Entity, line: 36
htmlParseStartTag: invalid element name in Entity, line: 36
Unexpected end tag : sub in Entity, line: 36

 -- (raw) entregas/HTM1/FC.html
htmlParseEntityRef: expecting ';' in Entity, line: 8
htmlParseStartTag: invalid element name in Entity, line: 26
htmlParseStartTag: invalid element name in Entity, line: 34
htmlParseEntityRef: expecting ';' in Entity, line: 36
htmlParseStartTag: invalid element name in Entity, line: 40
Unexpected end tag : sub in Entity, line: 40
htmlParseStartTag: invalid element name in Entity, line: 56
htmlParseStartTag: invalid element name in Entity, line: 60

 -- (raw) entregas/HTM1/HA.html
htmlParseStartTag: invalid element name in Entity, line: 12
htmlParseStartTag: invalid element name in Entity, line: 12
htmlParseEntityRef: expecting ';' in Entity, line: 14
htmlParseStartTag: invalid element name in Entity, line: 18

 -- (raw) entregas/HTM1/JL.html

 -- (raw) entregas/HTM1/PE.html

 -- (raw) entregas/HTM1/PI.html
htmlParseStartTag: invalid element name in Entity, line: 58
htmlParseEntityRef: no name in Entity, line: 90
htmlParseEntityRef: no name in Entity, line: 90
htmlParseStartTag: invalid element name in Entity, line: 118
htmlParseEntityRef: no name in Entity, line: 388
htmlParseStartTag: invalid element name in Entity, line: 463
htmlParseEntityRef: no name in Entity, line: 581
htmlParseStartTag: invalid element name in Entity, line: 835
htmlParseStartTag: invalid element name in Entity, line: 853
htmlParseEntityRef: expecting ';' in Entity, line: 960
htmlParseStartTag: invalid element name in Entity, line: 984
htmlParseStartTag: invalid element name in Entity, line: 1025
htmlParseStartTag: invalid element name in Entity, line: 1099
htmlParseStartTag: invalid element name in Entity, line: 1255
htmlParseStartTag: invalid element name in Entity, line: 1272
htmlParseEntityRef: no name in Entity, line: 1366
htmlParseEntityRef: no name in Entity, line: 1366
htmlParseStartTag: invalid element name in Entity, line: 1402
htmlParseEntityRef: expecting ';' in Entity, line: 1566
htmlParseStartTag: invalid element name in Entity, line: 1690

 -- (raw) entregas/HTM1/PN.html
htmlParseStartTag: invalid element name in Entity, line: 8
htmlParseEntityRef: no name in Entity, line: 30
htmlParseEntityRef: expecting ';' in Entity, line: 30
htmlParseEntityRef: expecting ';' in Entity, line: 30
htmlParseStartTag: invalid element name in Entity, line: 36
htmlParseStartTag: invalid element name in Entity, line: 82
htmlParseStartTag: invalid element name in Entity, line: 82
htmlParseStartTag: invalid element name in Entity, line: 82
htmlParseEntityRef: no name in Entity, line: 90
htmlParseStartTag: invalid element name in Entity, line: 100
htmlParseStartTag: invalid element name in Entity, line: 114
htmlParseStartTag: invalid element name in Entity, line: 120
htmlParseStartTag: invalid element name in Entity, line: 128
htmlParseStartTag: invalid element name in Entity, line: 146
Unexpected end tag : i in Entity, line: 146
htmlParseStartTag: invalid element name in Entity, line: 150
Unexpected end tag : sub in Entity, line: 150
htmlParseStartTag: invalid element name in Entity, line: 150
htmlParseStartTag: invalid element name in Entity, line: 166
htmlParseStartTag: invalid element name in Entity, line: 188
htmlParseEntityRef: expecting ';' in Entity, line: 206
htmlParseStartTag: invalid element name in Entity, line: 222
htmlParseStartTag: invalid element name in Entity, line: 268
htmlParseStartTag: invalid element name in Entity, line: 272
htmlParseStartTag: invalid element name in Entity, line: 284
htmlParseStartTag: invalid element name in Entity, line: 312
Unexpected end tag : i in Entity, line: 312
Invalid char in CDATA 0x1 in Entity, line: 330
Invalid char in CDATA 0x2 in Entity, line: 330
Invalid char in CDATA 0x2 in Entity, line: 330
htmlParseStartTag: invalid element name in Entity, line: 342
htmlParseEntityRef: expecting ';' in Entity, line: 372
htmlParseEntityRef: expecting ';' in Entity, line: 544
Unexpected end tag : sup in Entity, line: 552
htmlParseStartTag: invalid element name in Entity, line: 632
htmlParseStartTag: invalid element name in Entity, line: 680
Unexpected end tag : sub in Entity, line: 680
htmlParseStartTag: invalid element name in Entity, line: 716
htmlParseStartTag: invalid element name in Entity, line: 730
Unexpected end tag : i in Entity, line: 730
htmlParseStartTag: invalid element name in Entity, line: 730
Unexpected end tag : i in Entity, line: 730
Tag rd invalid in Entity, line: 732
htmlParseStartTag: invalid element name in Entity, line: 738
htmlParseStartTag: invalid element name in Entity, line: 746
htmlParseStartTag: invalid element name in Entity, line: 754
htmlParseStartTag: invalid element name in Entity, line: 758
htmlParseStartTag: invalid element name in Entity, line: 770
htmlParseStartTag: invalid element name in Entity, line: 774
htmlParseEntityRef: no name in Entity, line: 782
htmlParseStartTag: invalid element name in Entity, line: 796
Unexpected end tag : i in Entity, line: 796
htmlParseStartTag: invalid element name in Entity, line: 796
Unexpected end tag : i in Entity, line: 796
htmlParseStartTag: invalid element name in Entity, line: 808
htmlParseEntityRef: expecting ';' in Entity, line: 828
htmlParseEntityRef: expecting ';' in Entity, line: 828
htmlParseEntityRef: expecting ';' in Entity, line: 828
htmlParseEntityRef: expecting ';' in Entity, line: 828
htmlParseEntityRef: expecting ';' in Entity, line: 828
htmlParseEntityRef: expecting ';' in Entity, line: 828
htmlParseStartTag: invalid element name in Entity, line: 884
htmlParseEntityRef: expecting ';' in Entity, line: 886
htmlParseEntityRef: no name in Entity, line: 931
htmlParseStartTag: invalid element name in Entity, line: 941
htmlParseEntityRef: no name in Entity, line: 943
htmlParseStartTag: invalid element name in Entity, line: 949
htmlParseEntityRef: no name in Entity, line: 981
htmlParseEntityRef: no name in Entity, line: 981
htmlParseStartTag: invalid element name in Entity, line: 1019
Unexpected end tag : sup in Entity, line: 1019
htmlParseEntityRef: expecting ';' in Entity, line: 1041
error parsing attribute name in Entity, line: 1049
Tag hi invalid in Entity, line: 1049
htmlParseStartTag: invalid element name in Entity, line: 1095
htmlParseEntityRef: no name in Entity, line: 1121
htmlParseStartTag: invalid element name in Entity, line: 1169
htmlParseEntityRef: expecting ';' in Entity, line: 1175
htmlParseStartTag: invalid element name in Entity, line: 1201
htmlParseStartTag: invalid element name in Entity, line: 1201
htmlParseStartTag: invalid element name in Entity, line: 1211
htmlParseStartTag: invalid element name in Entity, line: 1390
htmlParseStartTag: invalid element name in Entity, line: 1392
htmlParseStartTag: invalid element name in Entity, line: 1434
htmlParseEntityRef: no name in Entity, line: 1434
htmlParseStartTag: invalid element name in Entity, line: 1446
htmlParseEntityRef: no name in Entity, line: 1470
htmlParseStartTag: invalid element name in Entity, line: 1470
htmlParseEntityRef: no name in Entity, line: 1490
htmlParseEntityRef: no name in Entity, line: 1490
htmlParseEntityRef: no name in Entity, line: 1490
htmlParseStartTag: invalid element name in Entity, line: 1518
htmlParseStartTag: invalid element name in Entity, line: 1524
htmlParseStartTag: invalid element name in Entity, line: 1568
htmlParseEntityRef: expecting ';' in Entity, line: 1596
htmlParseEntityRef: expecting ';' in Entity, line: 1596
htmlParseEntityRef: expecting ';' in Entity, line: 1596
htmlParseStartTag: invalid element name in Entity, line: 1606
htmlParseStartTag: invalid element name in Entity, line: 1608
htmlParseStartTag: invalid element name in Entity, line: 1610
htmlParseStartTag: invalid element name in Entity, line: 1644
htmlParseStartTag: invalid element name in Entity, line: 1666
htmlParseEntityRef: no name in Entity, line: 1782
htmlParseStartTag: invalid element name in Entity, line: 1901
htmlParseStartTag: invalid element name in Entity, line: 1917
htmlParseStartTag: invalid element name in Entity, line: 2005
htmlParseStartTag: invalid element name in Entity, line: 2062
htmlParseStartTag: invalid element name in Entity, line: 2084
htmlParseStartTag: invalid element name in Entity, line: 2138
htmlParseStartTag: invalid element name in Entity, line: 2138
htmlParseStartTag: invalid element name in Entity, line: 2162
Unexpected end tag : sup in Entity, line: 2162
htmlParseStartTag: invalid element name in Entity, line: 2202
htmlParseEntityRef: no name in Entity, line: 2253
htmlParseStartTag: invalid element name in Entity, line: 2309
Unexpected end tag : i in Entity, line: 2309
htmlParseStartTag: invalid element name in Entity, line: 2309
htmlParseStartTag: invalid element name in Entity, line: 2417
Unexpected end tag : i in Entity, line: 2417
htmlParseStartTag: invalid element name in Entity, line: 2489
htmlParseStartTag: invalid element name in Entity, line: 2505
htmlParseStartTag: invalid element name in Entity, line: 2525
htmlParseStartTag: invalid element name in Entity, line: 2601
htmlParseStartTag: invalid element name in Entity, line: 2671
htmlParseStartTag: invalid element name in Entity, line: 2685
htmlParseStartTag: invalid element name in Entity, line: 2685
htmlParseStartTag: invalid element name in Entity, line: 2807
htmlParseEntityRef: no name in Entity, line: 2825
htmlParseEntityRef: no name in Entity, line: 2825
htmlParseStartTag: invalid element name in Entity, line: 2863
htmlParseStartTag: invalid element name in Entity, line: 2867
htmlParseStartTag: invalid element name in Entity, line: 2933
htmlParseStartTag: invalid element name in Entity, line: 3021
htmlParseEntityRef: no name in Entity, line: 3095
htmlParseEntityRef: expecting ';' in Entity, line: 3095
htmlParseEntityRef: expecting ';' in Entity, line: 3095
htmlParseStartTag: invalid element name in Entity, line: 3171
htmlParseStartTag: invalid element name in Entity, line: 3183
htmlParseEntityRef: expecting ';' in Entity, line: 3201
htmlParseEntityRef: expecting ';' in Entity, line: 3263
htmlParseEntityRef: no name in Entity, line: 3289
htmlParseStartTag: invalid element name in Entity, line: 3309
htmlParseStartTag: invalid element name in Entity, line: 3309
htmlParseStartTag: invalid element name in Entity, line: 3327
htmlParseEntityRef: no name in Entity, line: 3339
htmlParseStartTag: invalid element name in Entity, line: 3407
htmlParseStartTag: invalid element name in Entity, line: 3407
htmlParseStartTag: invalid element name in Entity, line: 3459
htmlParseStartTag: invalid element name in Entity, line: 3487
htmlParseStartTag: invalid element name in Entity, line: 3503
htmlParseStartTag: invalid element name in Entity, line: 3525
htmlParseStartTag: invalid element name in Entity, line: 3585
htmlParseStartTag: invalid element name in Entity, line: 3595
htmlParseStartTag: invalid element name in Entity, line: 3613
htmlParseStartTag: invalid element name in Entity, line: 3635
htmlParseStartTag: invalid element name in Entity, line: 3635
htmlParseEntityRef: expecting ';' in Entity, line: 3657
htmlParseEntityRef: expecting ';' in Entity, line: 3657

**Comment by solangefpaulino** [comment]
Acho que agora a lista veio completo
Essa noite corrijo e substituo o arquivo no github OK!
Em 14/08/2015 18:18, "Peter" notifications@github.com escreveu:

**Comment by ppKrauss** [comment]
Arrumei todos, valendo HTM2 do #9.

---

## Ilustrações didáticas

Um caso típico de propagação de erro ocorria com o resumo PN1699, onde a porção final do texto era eliminada. Por usar o sinal menor seguido de "2B" formava uma tag, 

> `inconclusiva quanto ao material (<2B), necessitando assim de novos ECR com validade externa.<br>`

o o parser a interpretava até o final da próxima tag, ou seja, toda a string "`<2B), necessitando assim de novos ECR com validade externa.<br>`" foi reinterpretada como uma tag não-HTML `<2B>`, portanto descartada posteriormente.

O texto final ficava portanto truncado, `inconclusiva quanto ao material (`.
Com a correção de "`<2B`" para "`&lt;2B`" o texto foi recuperado, "`inconclusiva quanto ao material (&lt;2B), necessitando assim de novos ECR com validade externa`". Além dessa porção final o texto PN1699 teve também, devido ao fragmento "`duração < 12 meses`", uma longa porção de texto removida: "`12 meses` (...) `ECR foi de 24 meses`".

Todas essa correções ficam vizíveis comparando as versões (ex. diffMeld) de [entregas/HTM2/resumosOriginais.html](https://github.com/ppKrauss/SBPqO-2015/blob/master/entregas/HTM2/resumosOriginais.html).

Casos como  "`foldchange>2`" de HA004 em [HA.html](https://github.com/ppKrauss/SBPqO-2015/blob/master/entregas/HTM1/HA.html), apesar de invalidos, são corrigidos sem ambiguidade pelo `DOMDocument::loadHTML()`.
